### ISSUE TITLE
Valideer changes Dict-Like Type during adaption

### ISSUE THREAD

**Issue by ovanes** [podio/valideer#20]
I would like to use `OrderedDict` to maintain my data structure and in fact the YAML parser just does it properly, but after the parsing process `valideer` breaks my `OrderedDict` (I suppose in: https://github.com/podio/valideer/blob/master/valideer/validators.py#L585 where it hard-coded uses `dict`). Is there any chance to make it work with may be a custom mapping type, but still without having to define the schema with Object-like style definition?

**Comment by gsakkis** [comment]
Yeah this makes sense. Btw you linked to the `Mapping` validator which is different from `Object`; both hardcode the adapted type to `dict`. Can you post an example of your current schema and sample input to make sure we're on the same page (and also use it as a unit test)?

**Comment by ovanes** [comment]
@gsakkis sorry for misleading link, just quickly searched where dict is hard-coded.

Input YAML file
```yaml
asset_id: 123af45
data_source: editor

video_name: some-relative-path-to-video.mp4
image_name: some-preview-image.jpg

title:
  en_US: Title of my movie
  de_DE: Mein Filmtitel

short_description:
  en_US: |
    Short video description on what is going on there.

  de_DE: |
    Kurze Beschreibung des Videos und was da abspielt.
```

Valideer schema
```python
import valideer as V
from valideer import Enum, Pattern, String
from valideer_extensions import PathValidator

_asset_id = Pattern(r'[A-Fa-f0-9]+')
_supported_languages = Enum(('de_DE', 'en_US'))

_schema_def =\
{ 'properties':
  { '+target_locale': _supported_languages
  , 'default_locale': _supported_languages
  }
, '+asset_id': _asset_id
, '+data_source': Enum(('editor',))
, '+video_name': String()
, '+image_name': PathValidator()  # just checks if path exists, can be replaced with String() here
, '+title':
   { '+de_DE': String()
   , 'en_US': String()
   }
, '+short_description':
  { '+de_DE': String()
  , 'en_US': String()
  }
}

schema = V.parse(_schema_def)
```

Python Code to load YAML in OrderedDict instead of dict, taken from StackOverflow suggestion:

```python
import yaml
from collections import OrderedDict

def ordered_load(stream, Loader=yaml.Loader, object_pairs_hook=OrderedDict):
    class OrderedLoader(Loader):
        def construct_mapping(loader, node):
            loader.flatten_mapping(node)
            return object_pairs_hook(loader.construct_pairs(node))

    OrderedLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, OrderedLoader.construct_mapping)
    return yaml.load(stream, OrderedLoader)


with codecs.open(file_path, mode='r', encoding='utf-8') as input:
    data = ordered_load(input)
    data = schema.validate(data)
```
